- name: install apache2
  apt:
    name:
      - apache2
    state: present
    update_cache: yes
    cache_valid_time: 3600
  become: yes

- name: start apache2
  service:
    name: apache2
    state: started
    enabled: yes  # Assurez-vous que nginx démarre au démarrage du système
  become: yes

- name: deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html
  become: yes 
