
- name: Playbook pour la gestion des serveurs 
  hosts: all 
  become: yes 
  vars:
    ansible_ssh_private_key_file: / root/.ssh/id_rsa
    ansible_ssh_passphrase: votre_passphrase_ici
    ansible user: jenkins
tasks:
 ⁃	name: Ajouter la clé d'hôte au fichier known_hosts 
 ansible-builtin. known_hosts:
 path: /root/-ssh/known_hosts name: 192.168.64.9
 key: "{ lookup( ansible builtin. file', '/root/-ssh/known_hosts') }}"
name: Exemple de tâche 
debug:
    msg: "Ceci est un exemple de tâche"

