all:
  hosts:
    192.168.64.11:
      ansible_user: jenkins
      ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa

    192.168.64.8:  # Ajout de la machine distante
      ansible_user: root  # Ou un autre utilisateur avec accès SSH
      ansible_ssh_private_key_file: /var/lib/jenkins/.ssh/id_rsa
      ansible_host: 192.168.64.8  # Assurez-vous que l'IP est correcte
